#!/bin/bash

. $TEST_ROOT_DIR/run-test-common

set -x
set -e -o pipefail

# This test case is to test Java Evaluation works with the same setup of users.
# The eval test uses some pretrained models which are not part of the CNTK repository itself
# We use the dataset from an external location specified using an environment variable
if [[ -z "$CNTK_EXTERNAL_TESTDATA_SOURCE_DIRECTORY" || ! -d "$CNTK_EXTERNAL_TESTDATA_SOURCE_DIRECTORY" ]]; then
  echo This test uses external data that is not part of the CNTK repository. Environment variable CNTK_EXTERNAL_TESTDATA_SOURCE_DIRECTORY must be set to point to the external test data location.
  exit 1
fi

# Copy pretrained models and data
if [ "$OS" == "Windows_NT" ]; then
  TestDataDir=`cygpath -au "$CNTK_EXTERNAL_TESTDATA_SOURCE_DIRECTORY/Bindings/Java"`
else
  TestDataDir="$CNTK_EXTERNAL_TESTDATA_SOURCE_DIRECTORY/Bindings/Java"
fi

LocalDataDir="$TEST_ROOT_DIR/../../bindings/java/JavaEvalTest/data"
if [ ! -d "$LocalDataDir" ]; then
  mkdir "$LocalDataDir"
fi
cp "$TestDataDir"/* "$LocalDataDir"

if [ "$OS" == "Windows_NT" ]; then
  # Run the evaluation test
  DllDir=`cygpath -aw "$TEST_BIN_DIR"`

  # TODO: run in TEST_BIN_DIR, so that no need to change PATH. Need to change sample how to read data.
  cd $LocalDataDir/..
  PATH="$PATH:$TEST_BIN_DIR"
  java.exe -Djava.library.path=$DllDir -classpath "$DllDir\java;$DllDir\java\cntk.jar" Main $TEST_FLAVOR

else
  # Run the evaluation test
  CntkRoot=$TEST_ROOT_DIR/../..

  TEST_LIB_DIR=$TEST_BUILD_LOCATION/$TEST_FLAVOR/lib
  TEST_LIB_JAVA_DIR=$TEST_LIB_DIR/java
  export LD_LIBRARY_PATH=$TEST_LIB_DIR:$LD_LIBRARY_PATH
  cd $LocalDataDir/..
  java -classpath "$TEST_LIB_JAVA_DIR:$TEST_LIB_JAVA_DIR/cntk.jar" $TEST_LIB_JAVA_DIR/Main $TEST_FLAVOR
fi
